### ISSUE TITLE
Please include requirement.txt in this project

### ISSUE THREAD

**Issue by ShubhamNagure** [ShubhamNagure/Selenium_with_python#1]
Add and review this code and include requirement.txt mainly include a driver for the firefox browser.

**Comment by sawyer1997** [comment]
@ShubhamNagure Can I please pick this one?

**Comment by ShubhamNagure** [comment]
@sawyer1997 Yes, why not. Please go ahead.

**Comment by sawyer1997** [comment]
Hi @ShubhamNagure, please review the PR, and let me know if there's anything else required to be done.
